### ISSUE TITLE
Pre-transfer audit

### ISSUE THREAD

**Issue by gadomski** [constantinius/stactools-datacube#2]
Thanks for the package @constantinius! Here's a list of things I found while looking through -- once these get fixed up, we can transfer this to **stac-utils**:

- [x] #1 
- [x] Remove or populate `tests/test_commands.py` -- no reason to keep around commented-out files, that's what version control is good for :-)
- [x] Same for the commented out sections of `commands.py`
- [x] It looks like there's still a lot of `ephemeral` words scattered around the repo -- unclear if the rename script didn't work properly, or what. But those should be updated to `datacube`
- [x] The example item's asset href is incorrect -- it's a relative href, but is not correct relative to the file's location. Should be `../../tests/data/sresa1b_ncar_ccsm3-example.nc`.

Once these items are done, we'll move it over! I _think_ that the procedure will look like:
1. You transfer this repo to me
2. I transfer it to **stac-utils**

But we'll figure it out.

**Comment by constantinius** [comment]
@gadomski Very well, thanks!

> Remove or populate tests/test_commands.py -- no reason to keep around commented-out files, that's what version control is good for :-)

> Same for the commented out sections of commands.py

Yes!
 
>  It looks like there's still a lot of ephemeral words scattered around the repo -- unclear if the rename script didn't work properly, or what. But those should be updated to datacube

I actually was not aware of the command

> The example item's asset href is incorrect -- it's a relative href, but is not correct relative to the file's location. Should be ../../tests/data/sresa1b_ncar_ccsm3-example.nc

That was actually not meant for that... Hmm, I'll think about it.

**Comment by constantinius** [comment]
@gadomski This is in theory done, but there seem to be issues in the CI, possibly related to the fact that the repo is called `stactools-datacube` and not `datacube`

So, how to continue?

**Comment by gadomski** [comment]
I think those issues should be fixed by https://github.com/constantinius/stactools-datacube/pull/3. I had to tweak the Dockerfile and the pre-commit versions, and I just blew away the docker publishing stuff -- I don't find it very useful (I recently remove it from the template in https://github.com/stactools-packages/template/pull/75).

**Comment by gadomski** [comment]
Okay, I think we're good. If you transfer owernship to @gadomski, I can then transfer it to @stactools-packages (and reduce its name to `datacube`)

**Comment by constantinius** [comment]
I tried to transfer the repo, but I get: `gadomski already has a repository in the constantinius/stactools-datacube network`

**Comment by gadomski** [comment]
I deleted my fork, so if you try again _hopefully_ it will work this time.

**Comment by gadomski** [comment]
We're here! Thanks for the iterations, @constantinius!
